[project]
site_name = "Nanopore barcoding pipeline"
site_description = " Infer DNA barcodes fom recent (R10.4) Nanopore sequence data using a DADA2-based pipeline "
site_author = "Markus Schlegel"
site_url = "markschl.github.io/dada-ont-barcoding"
repo_url = "https://github.com/markschl/dada-ont-barcoding"
edit_uri = "edit/main/docs/"
nav = [
  "index.md",
  "primers.md",
  "lab.md",
  {"Analysis" = [
     "analysis/index.md",
     "analysis/basecalling.md",
     "analysis/workflow.md",
  ]},
  "curation.md"
]

[project.theme]
language = "en"
features = [
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.tabs.link",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
